### ISSUE TITLE
When will we add the start of pc support in the universalmine-mp repo?

### ISSUE THREAD

**Issue by matthew4444** [UniversalMine/UniversalMine-MP#2]
When will we add the start of pc support in the universalmine-mp repo? i was thinking of starting the pc support in the pc base repo and injecting it into the universalmine-mp src folder, as a core, something like a core?

**Comment by matthew4444** [comment]
I REALLY LIKE HOW THE PROJECT IS GOING THOUGH :)

**Comment by RedstoneAlmeida** [comment]
Is possible to do in the base, and also I have idea to make a system of proxy, type Synapse, only that simpler, to work it is necessary to correct the package errors, in the TransationProtocol, and then to add all the packages of the minecraft

**Comment by matthew4444** [comment]
thx

**Comment by RedstoneAlmeida** [comment]
Help-me to correct the package errors in TranslationProtocol.php

**Comment by matthew4444** [comment]
idk php :(

**Comment by RedstoneAlmeida** [comment]
:c

**Comment by RedstoneAlmeida** [comment]
![image](https://cloud.githubusercontent.com/assets/15146680/21696698/5285389a-d376-11e6-97ad-fbb94054ecd6.png)
First Working 💃

**Comment by matthew4444** [comment]
I know what bug that is, its what happens when u use a old world before an mcpe 1.0.0 client joins and generates a new world in the server via commands,plz try a new one, here is a link to a test one, tell me if it works plz?

**Comment by matthew4444** [comment]
[MSPLEEF.zip](https://github.com/UniversalMine/UniversalMine-MP/files/688602/MSPLEEF.zip)

**Comment by RedstoneAlmeida** [comment]
ok

**Comment by RedstoneAlmeida** [comment]
is not work again, 
![image](https://cloud.githubusercontent.com/assets/15146680/21700954/144f1032-d38a-11e6-8f55-549d4bcc8458.png)

**Comment by matthew4444** [comment]
omg. thats a different glitch then?????? becuase i used that map yesterday on the exact fork ur using for ppmp , aka "ElyWIng"

**Comment by matthew4444** [comment]
we need to fix the glitch, i hope we can find the glitch

**Comment by matthew4444** [comment]
look what i found https://github.com/H4PM/Elywing/commit/5167e49835bfb9bab50d9787241344ddb54dd0df

**Comment by matthew4444** [comment]
when we make the 1st working release, can you help me learn pocketmine coding or php plz @RedstoneAlmeida . and look what i found H4PM/Elywing@5167e49

**Comment by RedstoneAlmeida** [comment]
Okay @matthew4444

**Comment by RedstoneAlmeida** [comment]
i'm use Genisys :c

**Comment by RedstoneAlmeida** [comment]
![screenshot_53](https://cloud.githubusercontent.com/assets/15146680/21723712/a0467a88-d418-11e6-8c74-5b5d102a8779.png)
- I'm used mcregion, it's work!
```yaml
level-settings:
 #The default format that levels will use when created
 default-format: mcregion
 #If true, converts from a format that is not the default to the default format on load
 #NOTE: This is currently not implemented
 convert-format: false
 #Automatically change levels tick rate to maintain 20 ticks per second
 auto-tick-rate: false
 auto-tick-rate-limit: 20
 #Sets the base tick rate (1 = 20 ticks per second, 2 = 10 ticks per second, etc.)
 base-tick-rate: 1
 #Tick all players each tick even when other settings disallow this.
 always-tick-players: false
```
